export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_TANDA = 'SET_CURRENT_TANDA';
export const SET_CURRENT_SUBGROUP = 'SET_CURRENT_SUBGROUP';
export const RESET_CURRENT_TANDA = 'RESET_CURRENT_TANDA';
export const REMOVE_CURRENT_TANDA = 'REMOVE_CURRENT_TANDA';
